- name: Copy ssh
  copy:
    src: config_opal
    dest: /home/root/.ssh/
    mode: '0600'


- name: modify config ssh
  lineinfile:
    dest: ~/.ssh/config 
    state: present
    regexp: Include ~/.ssh/config_opal
